# Generated by Django 2.2.16 on 2022-08-20 10:16

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1200, verbose_name='Category name')),
                ('image', models.ImageField(blank=True, upload_to='category', verbose_name='Category image')),
                ('slug', models.SlugField(editable=False, null=True, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Burda xeberin basligi yazilir', max_length=1500, verbose_name='Post title')),
                ('content', models.TextField(blank=True, verbose_name='Post content')),
            ],
            options={
                'verbose_name': 'Slayd',
                'verbose_name_plural': 'Slaydlar',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Burda xeberin basligi yazilir', max_length=1500, verbose_name='Post title')),
                ('preview_count', models.IntegerField(default=10, null=True, verbose_name='Preview count')),
                ('content', ckeditor.fields.RichTextField(blank=True, verbose_name='Post content')),
                ('create_time', models.DateTimeField(blank=True, null=True, verbose_name='Post date')),
                ('image', models.ImageField(null=True, upload_to='post', verbose_name='Shekil elave et')),
                ('draft', models.BooleanField(default=True, verbose_name='Saytda yayimlansin?')),
                ('slug', models.SlugField(editable=False, null=True, unique=True, verbose_name='Slug')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data', to='post.Category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Xeber',
                'verbose_name_plural': 'Xeberler',
            },
        ),
        migrations.CreateModel(
            name='Galery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='post/galery', verbose_name='Image')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galery_post', to='post.Post', verbose_name='Post')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Galery images',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date')),
                ('content', models.TextField(verbose_name='Comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_post', to='post.Post', verbose_name='Post')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
