# Generated by Django 2.2.16 on 2022-08-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Xeber', 'verbose_name_plural': 'Xeberler'},
        ),
        migrations.AddField(
            model_name='post',
            name='create_time',
            field=models.DateTimeField(null=True, verbose_name='Post date'),
        ),
    ]
