# Generated by Django 2.2.16 on 2022-08-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20220824_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_text', models.CharField(max_length=1500, verbose_name='Sayt haqqında(SEO mətni)')),
                ('meta_keywords', models.CharField(blank=True, max_length=1500, null=True, verbose_name='Meta Keywords')),
                ('site_title', models.CharField(max_length=1500, verbose_name='Saytın başlığı')),
                ('email', models.CharField(max_length=1500, null=True, verbose_name='Email')),
                ('number', models.CharField(max_length=1500, null=True, verbose_name='Nömrə')),
                ('adress', models.CharField(max_length=1500, null=True, verbose_name='Ünvan')),
                ('g_adress', models.CharField(blank=True, max_length=1500, null=True, verbose_name='Google Map linki')),
                ('logo', models.FileField(blank=True, upload_to='', verbose_name='Qara logo(163x38)')),
                ('dark_logo', models.FileField(blank=True, null=True, upload_to='', verbose_name='Ağ logo(163x38)')),
                ('favicon', models.FileField(blank=True, null=True, upload_to='', verbose_name='favicon(32x32)')),
                ('proloader_logo', models.FileField(blank=True, help_text='Sayt açılanda yükənən logo', null=True, upload_to='', verbose_name='Preloader logo(163x38)')),
                ('footer_logo', models.FileField(blank=True, help_text='Saytın aşağısındakı logo', null=True, upload_to='', verbose_name='Footer logo(163x38)')),
                ('facebook', models.CharField(blank=True, max_length=1500, verbose_name='Facebook')),
                ('instagram', models.CharField(blank=True, max_length=1500, verbose_name='İnstagram')),
                ('linkedin', models.CharField(blank=True, max_length=1500, verbose_name='Linkedin')),
                ('youtube', models.CharField(blank=True, max_length=1500, verbose_name='Youtube')),
                ('medium', models.CharField(blank=True, max_length=1500, verbose_name='Medium')),
                ('google_business', models.CharField(blank=True, max_length=1500, null=True, verbose_name='Google Business')),
                ('twitter', models.CharField(blank=True, max_length=1500, null=True, verbose_name='Twitter')),
                ('slug', models.SlugField(editable=False, verbose_name='Slug')),
                ('c_meta_title', models.CharField(max_length=1500, null=True, verbose_name='Əlaqə Meta title')),
                ('c_meta_keywords', models.CharField(blank=True, max_length=1500, null=True, verbose_name='Əlaqə Meta keywords')),
                ('c_meta_description', models.TextField(help_text='Meta descriptionda max. 150 hərf ola bilər!', max_length=160, null=True, verbose_name='Əlaqə Meta description')),
                ('n_meta_title', models.CharField(max_length=1500, null=True, verbose_name='Xəbər Meta title')),
                ('n_meta_description', models.TextField(help_text='Meta descriptionda max. 150 hərf ola bilər!', max_length=160, null=True, verbose_name='Xəbər Meta description')),
            ],
            options={
                'verbose_name': 'Tənzimləmə',
                'verbose_name_plural': 'Tənzimləmələr',
                'ordering': ['-id'],
            },
        ),
    ]
