# Generated by Django 2.2.16 on 2022-08-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20220806_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='Burda xeberin basligi yazilir', max_length=1500, verbose_name='Post title'),
        ),
    ]
