# Generated by Django 2.2.16 on 2022-09-04 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTrue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1200, verbose_name='Title')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='truepost', to='post.Post', verbose_name='Post')),
            ],
            options={
                'verbose_name': 'Post True',
                'verbose_name_plural': 'Post True',
            },
        ),
    ]
