# Generated by Django 2.2.16 on 2022-08-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20220806_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=True, verbose_name='Saytda yayimlansin?'),
        ),
    ]
