# Generated by Django 2.2.16 on 2022-08-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_post_draft'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Burda xeberin basligi yazilir', max_length=1500, verbose_name='Post title')),
                ('content', models.TextField(blank=True, verbose_name='Post content')),
            ],
            options={
                'verbose_name': 'Slayd',
                'verbose_name_plural': 'Slaydlar',
            },
        ),
    ]
