# Generated by Django 2.2.16 on 2022-08-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='post', verbose_name='Shekil elave et'),
        ),
    ]
