# Generated by Django 2.2.16 on 2022-08-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(editable=False, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
