# Generated by Django 2.2.16 on 2022-08-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_auto_20220818_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(editable=False, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
