# Generated by Django 2.2.16 on 2022-08-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Sekil elave et'),
        ),
    ]
