# Generated by Django 2.2.16 on 2022-08-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_myuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='usersex',
            field=models.IntegerField(choices=[(1, 'Kişi'), (2, 'Qadın')], null=True, verbose_name='Cins'),
        ),
    ]
