# Generated by Django 2.2.16 on 2022-08-20 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_myuser_usersex'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='usersex',
            new_name='usertype',
        ),
    ]
